blank_issues_enabled: false
contact_links:
  - name: Octoatask.new related issues
    url: https://github.com/octotask/octotask.new/issues/new/choose
    about: Report issues related to Octoatask.new (not Octoatask.diy)
  - name: Chat
    url: https://thinktank.ottomator.ai
    about: Ask questions and discuss with other Octoatask.diy users.
